### ISSUE TITLE
Download and streaming produces 403 Forbidden

### ISSUE THREAD

**Issue by DivineDominion** [dohliam/ccmixter-download#1]
This is puzzling me: this script and also `wget` won't download just any mp3 file from ccMixter. `curl -I` also returns 403 Forbidden. 

If you copy the download link URL and paste in into the browser, also 403 Forbidden.

**Unless* you click the link at least once. Then it works like a charm.

In the [React.js source for the website](https://github.com/victor-stone/dig-react/search?q=download) I only found 1 JavaScript click event for the download button, and that logs the download for analytics. There's no cookie settings that denote "this browser can download this file" or any other filter that would toggle a flag for downloadability on.

Ideas welcome :)

**Comment by dohliam** [comment]
Thanks for raising this issue! I tried this and got the same error. It looks like ccmixter.org has disabled direct access to audio files in their Apache server config, which is unfortunate and -- as you noticed -- breaks this script.

With regard to clicking the links first in the browser, I would guess that this probably works because they are checking for a referrer before serving the files (also easily doable by configuring Apache). Of course, this won't help much if you are trying to access the files from outside the browser.

You can test this out in curl by using the `--referer` option. I just tried this using "http://ccmixter.org/" as the referrer string and it worked, so it's definitely possible. It seems like it would be a bit inelegant to hardcode this in the script, but it looks like it won't work otherwise.

**Comment by DivineDominion** [comment]
@dohliam Geeeeez, I didn't think of that! Thanks for the pointer and figuring this out
